# Generated by Django 5.0.6 on 2024-06-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pelicula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("anio_estreno", models.IntegerField()),
                ("director", models.CharField(max_length=200)),
                ("especial", models.BooleanField(default=False)),
            ],
        ),
    ]
