# Generated by Django 5.0.6 on 2024-06-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("peliculas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("clave", models.CharField(max_length=128)),
                ("nombre", models.CharField(max_length=200)),
                ("fecha_nacimiento", models.DateField()),
            ],
        ),
    ]
